-- Draft local Supabase schema inferred from the bundled client.
-- This is a starting point if you want to replace server.mjs with real local Supabase.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.customers (
  user_id uuid primary key references auth.users(id) on delete cascade,
  subscription text default 'free',
  seat_count integer default 0,
  status text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.team_members (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  has_seat boolean default false,
  seat_released_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(team_id, user_id)
);

create table if not exists public.team_invites (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  email text not null,
  with_seat boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(team_id, email)
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  short_id text not null unique,
  user_id uuid references auth.users(id) on delete set null,
  team_id uuid references public.teams(id) on delete set null,
  title text,
  public boolean default false,
  document jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.document_shares (
  id uuid primary key default gen_random_uuid(),
  document_id bigint not null references public.documents(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz default now(),
  unique(document_id, email)
);

create table if not exists public.document_revisions (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.documents(id) on delete cascade,
  revision_number integer not null,
  message text,
  author_id uuid references auth.users(id) on delete set null,
  snapshot jsonb not null,
  created_at timestamptz default now(),
  unique(document_id, revision_number)
);

create table if not exists public.part_libraries (
  user_id uuid primary key references auth.users(id) on delete cascade,
  part_library jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.editor_state (
  user_id uuid references auth.users(id) on delete cascade,
  document_id bigint references public.documents(id) on delete cascade,
  updated_at timestamptz default now(),
  primary key(user_id, document_id)
);

create or replace function public.get_effective_plan()
returns text language sql stable as $$ select 'free'::text $$;

create or replace function public.is_team_active(team uuid)
returns boolean language sql stable as $$ select false $$;

create or replace function public.get_my_invites()
returns setof public.team_invites language sql stable as $$ select * from public.team_invites where false $$;

create or replace function public.get_team_members(team uuid)
returns table(id uuid, team_id uuid, user_id uuid, email text, name text, has_seat boolean)
language sql stable as $$
  select tm.id, tm.team_id, tm.user_id, u.email, p.name, tm.has_seat
  from public.team_members tm
  left join auth.users u on u.id = tm.user_id
  left join public.profiles p on p.id = tm.user_id
  where tm.team_id = team;
$$;

create or replace function public.get_revision_authors(doc_id bigint)
returns table(author_id uuid, name text)
language sql stable as $$
  select distinct dr.author_id, p.name
  from public.document_revisions dr
  left join public.profiles p on p.id = dr.author_id
  where dr.document_id = doc_id;
$$;

create or replace function public.create_document_revision(doc_id bigint, msg text)
returns public.document_revisions language plpgsql as $$
declare
  d public.documents;
  next_no integer;
  rev public.document_revisions;
begin
  select * into d from public.documents where id = doc_id;
  if not found then raise exception 'Document not found'; end if;
  select coalesce(max(revision_number), 0) + 1 into next_no from public.document_revisions where document_id = doc_id;
  insert into public.document_revisions(document_id, revision_number, message, author_id, snapshot)
  values(doc_id, next_no, msg, auth.uid(), d.document)
  returning * into rev;
  return rev;
end $$;

create or replace function public.restore_document_revision(rev_id bigint)
returns table(snapshot jsonb, updated_at timestamptz) language plpgsql as $$
declare
  rev public.document_revisions;
  ts timestamptz := now();
begin
  select * into rev from public.document_revisions where id = rev_id;
  if not found then raise exception 'Revision not found'; end if;
  update public.documents set document = rev.snapshot, updated_at = ts where id = rev.document_id;
  return query select rev.snapshot, ts;
end $$;
